# 应用名称
spring:
  application:
    name: blog-serve
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    active: dev


server:
  port: 8080
  servlet:
    context-path: /api



